Models/Item.cs
using System.ComponentModel.DataAnnotations; 

public class Item
{
    [Key] 
    public int ItemsId { get; set; }

    [Required]
    public string ItemDesc { get; set; }

    public decimal ItemCost { get; set; }
}

Models/OrderDetails.cs
using System.ComponentModel.DataAnnotations;
public class OrderDetails
{
    [Key] 
    public int OrderedDetailsId { get; set; }

    public int OrderedIDMaster { get; set; }

    public int Item { get; set; }

    public int Quantity { get; set; }

    public decimal Cost { get; set; }
}

Models/OrderMaster.cs
using System.ComponentModel.DataAnnotations;
using System;

public class OrderMaster
{
    [Key]
    public int OrderId { get; set; }

    public string CustomerID { get; set; }

    public DateTime OrderedDate { get; set; }

    public decimal OrderedAmount { get; set; }

}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class ItemsController : Controller
    {
        private _DbContext db = new _DbContext();

        // GET: Items
        public async Task<ActionResult> Index()
        {
            return View(await db.Items.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        [HttpPost]
        [ValidateAntiForgeryToken] // to avoid Cross-Site Request Forgery (CSRF)
                                   // attacks occur when an attacker tricks a user into unknowingly
                                   // submitting a malicious request to a web application on which the user is authenticated.
        public async Task<ActionResult> Create(Item item)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(item);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Items/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ItemsId,ItemDesc,ItemCost")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost/*, ActionName("Delete")*/]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Item item = await db.Items.FindAsync(id);
            db.Items.Remove(item);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;


namespace WebApp.Controllers
{
    public class OrderController : Controller
    {
        private _DbContext db = new _DbContext();
        // GET: Order
        public async Task<ActionResult> CheckOut()
        {
            return View(await db.Items.ToListAsync());
        }

        [HttpPost]/*, ActionName("Delete")*/
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> OrderList(List<OrderDetails> items, string customerId, decimal totalCost)
        {
            try
            {
                if (items != null && ModelState.IsValid)
                {
                    //[Bind(Include = "ItemsId,ItemDesc,ItemCost")]
                    decimal orderAmount = totalCost;
                    OrderMaster order = new OrderMaster();
                    order.OrderedDate = DateTime.Now;
                    order.CustomerID = customerId;
                    order.OrderedAmount = orderAmount;

                    db.OrderMasters.Add(order);
                    await db.SaveChangesAsync();

                    //OrderMaster get_customerId = await db.OrderMasters.FindAsync(customerId);
                    OrderMaster get_customerId = await db.OrderMasters.FirstOrDefaultAsync(o => o.CustomerID == customerId);

                    foreach (var item in items)
                    {
                        OrderDetails set_orderDetails = new OrderDetails();
                        set_orderDetails.OrderedIDMaster = get_customerId.OrderId;
                        set_orderDetails.Item = item.Item;
                        set_orderDetails.Quantity = item.Quantity;
                        set_orderDetails.Cost = item.Cost;
                        db.OrderDetails.Add(set_orderDetails);
                    }
                    await db.SaveChangesAsync();
                    return Json(new { success = true });
                }
            }
            catch (Exception error)
            {
                Console.WriteLine(error.ToString());
            }

            return Json(new { success = false, errorMessage = "Error occurred while placing order." });
        }
    }
}

Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace YourNamespace.Controllers
{
    public class ReportController : Controller
    {
        private _DbContext db = new _DbContext();

        // GET: Report
        public ActionResult Index()
        {
            //ViewBag.CustomerIDs = db.OrderMasters.Select(o => new { o.CustomerID }).Distinct().ToList();
            ViewBag.CustomerIDs = db.OrderMasters.Select(o => o.CustomerID.ToString()).Distinct().ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Search(string customerId)
        {
            var orders = db.OrderMasters.Where(o => o.CustomerID == customerId).ToList();

            return PartialView("_OrderList", orders);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>WalMart</h1>
    <img src="~/images/walmart.jpeg" />
    <br/>
    <br/>
    <p class="lead">
        WalMart's stores serve as one-stop destinations for consumers, offering everything from groceries and household
        essentials to electronics, clothing, and automotive supplies. With a commitment to low prices and convenient shopping
        experiences, WalMart has become a household name synonymous with value and variety.
    </p>
</div>

Views/Items/Create.cshtml
@model Item

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ItemDesc, "Item Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemCost, "Item Cost", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Items/Delete.cshtml
@model Item

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h4>Are you sure you want to delete this?</h4>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            <span>Item Description</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemDesc)
        </dd>

        <dt>
            <span>Item Cost</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemCost)
        </dd>

    </dl>

    @*@using (Html.BeginForm())*@
    @using (Html.BeginForm("DeleteConfirmed", "Items", new { id = Model.ItemsId }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Items/Details.cshtml
@model Item

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <span>Item Description</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemDesc)
        </dd>

        <dt>
            <span>Item Cost</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemCost)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ItemsId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Items/Edit.cshtml
@model Item

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ItemsId)

        <div class="form-group">
            @Html.LabelFor(model => model.ItemDesc, "Items Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemCost, "Items Cost", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Items/Index.cshtml
@model IEnumerable<Item>

@{
    ViewBag.Title = "Index";
}

<h2>Description</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            <span>Item Description</span>
        </th>
        <th>
            <span>Item Cost</span>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ItemDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemCost)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ItemsId }) |
            @Html.ActionLink("Details", "Details", new { id = item.ItemsId }) |
            @*@Html.ActionLink("Delete Name", "Delete", new { id=item.ItemsId })*@
            @Html.ActionLink("Delete", "Delete", "Items", new { id = item.ItemsId }, null)
        </td>
    </tr>
}

</table>

Views/Order/CheckOut.cshtml
@model IEnumerable<Item>

@{
    ViewBag.Title = "CheckOut Screen";
}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checkout</title>
    <!-- Include jQuery library -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <h2>Items</h2>
    <table class="table table-responsive">
        <tr>
            <th><span>ID</span></th>
            <th><span>Item</span></th>
            <th><span>Item Cost</span></th>
            <th><span>Quantity</span></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.ItemsId)</td>
                <td>@Html.DisplayFor(modelItem => item.ItemDesc)</td>
                <td>@Html.DisplayFor(modelItem => item.ItemCost)</td>
                <td>
                    <input type="checkbox" class="item-checkbox" value="@item.ItemsId" />
                    <input type="number" class="item-quantity" value="1" min="0" />
                </td>
            </tr>
        }
    </table>

    <div>
        <button class="btn btn-primary" id="submit" type="button">Checkout</button>
    </div>

    <script>
        function generateGUID() {
            var guid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
                var r = Math.random() * 16 | 0, v = c === 'x' ? r : (r & 0x3 | 0x8);
                return v.toString(16);
            });
            return guid;
        }

        $(document).ready(function () {
            $("#submit").click(function () {
                debugger;
                var totalCost = 0;
                var customerId = generateGUID();
                var items = [];

                $(".item-checkbox:checked").each(function () {
                    let itemId = $(this).val();
                    let quantity = $(this).closest("tr").find(".item-quantity").val();
                    let itemCost = $(this).closest("tr").find("td:nth-child(3)").text();
                    let cost = parseFloat(quantity) * parseFloat(itemCost);
                    items.push({ Item: itemId, Quantity: quantity, Cost: cost });
                    totalCost += cost;
                });

                $.ajax({
                    url: "/Order/OrderList",
                    method: "POST",
                    data: { items: items, customerId: customerId, totalCost: totalCost },
                    success: function (response) {
                        if (response.success) {
                            alert("Order placed successfully!");
                            window.location.href = "/Home/Index";
                        } else {
                            alert("Error occurred while placing order: " + response.errorMessage);
                        }
                    },
                    error: function (xhr, status, error) {
                        debugger;
                        alert("Error occurred while placing order.");
                    }
                });
            });
        });

    </script>

</body>

Views/Report/Index.cshtml
@{
    ViewBag.Title = "Customer-wise Orders";
}

<h2>Customer-wise Orders</h2>

<div>
    <h3>Select Customer ID to Search Orders:</h3>
    <table class="table table-responsive">
        @*<thead>
            <tr>
                <th>Customer ID</th>
            </tr>
        </thead>*@
        <tbody>
            @foreach (var order in ViewBag.CustomerIDs)
            {
                <tr>
                    <td>
                        <button type="button" class="btn btn-link customer-id-btn" data-customerid="@order">@order</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<hr />

@using (Html.BeginForm("Search", "Report", FormMethod.Post, new { id = "searchForm" }))
{
    <div class="form-group">
        @Html.Label("Customer ID:")
        @Html.TextBox("customerId", null, new { @class = "form-control", id = "customerId" })
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
}
</br>
<div id="orderListContainer"></div>

@section scripts {
    <script>
        $(function () {
            $('.customer-id-btn').click(function () {
                var customerId = $(this).data('customerid');
                $('#customerId').val(customerId);
                $('#searchForm').submit();
            });

            $('#searchForm').submit(function (e) {
                e.preventDefault();
                var customerId = $('#customerId').val();
                $.ajax({
                    url: '@Url.Action("Search", "Report")',
                    type: 'POST',
                    data: { customerId: customerId },
                    success: function (data) {
                        $('#orderListContainer').html(data);
                    },
                    error: function () {
                        alert('Error occurred while searching orders.');
                    }
                });
            });
        });
    </script>
}

Views/Report/_OrderList.cshtml
@model List<OrderMaster>

<table class="table table-responsive">
    <tr>
        <th>Order ID</th>
        <th>Customer ID</th>
        <th>Ordered Date</th>
        <th>Ordered Amount</th>
    </tr>
    @foreach (var order in Model)
    {
        <tr>
            <td>@order.OrderId</td>
            <td>@order.CustomerID</td>
            <td>@order.OrderedDate</td>
            <td>@order.OrderedAmount</td>
        </tr>
    }
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WalMart</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">

                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Walmart", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cart", "CheckOut", "Order")</li>
                    <li>@Html.ActionLink("Orders Report", "Index", "Report")</li>
                    <li>@Html.ActionLink("Store", "Index", "Items")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()


    </div>
    
    <footer>
        <hr />
        <p class="container">&copy; @DateTime.Now.Year - WalMart</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>